### ISSUE TITLE
Nvidia Power Limit for internal GPU

### ISSUE THREAD

**Issue by sridhar-singhal** [Lulech23/NVIDIA-Power-Limit#1] opened 2021-02-17 04:36 UTC
Window's new power management system is not very good. After an update which took place somewhere in march, the GPU in my laptop (GTX1660ti Max Q) runs very hot, without any load ( 60-65C) when connected to the charger. This bumps up the temperature of every component in my laptop. This does not happen when the charger is disconnected.
I noticed in HWmonitor that the power limit goes from 1 to 0 when the charger is connected and I figure this is the problem.

This is not exactly an issue and I sorry to use this place as a forum, but could you create something for this situation. It seems to be similar.

Thanking You
Yours faithfully

**Comment by Lulech23** [comment] 2021-02-17 05:29
If the GPU doesn't have any load, it's not the cause of heat generation. Raising the power limit does not mean the GPU is drawing more power, it just means it _can_ if it needs to.

The increased temperatures on the GPU are almost certainly the _result_ of the rest of the system heating up, not the cause. It could even be that charging is itself what's generating heat. Are you charging at a faster rate, perhaps?

Best of luck in identifying the cause, but since it's unrelated to this script or even the GPU I'm closing this one.

**Closed as completed by Lulech23** 2021-02-17 05:29 UTC

**Comment by sridhar-singhal** [comment] 2021-02-17 07:02
Thank you for your response.

I checked using Nvidia-smi, the utilisation is zero, but the power draw is
about 22 watts when plugged in. When charger is disconnected, the power
draw is 3-4 watts. Utilisation is zero again.
Further Nvidia-smi can not be used to set power limits. Neither does it
list any maximum or minimum power limits (N/A).
I am extremely sorry to trouble you with this but I have been unable to fix
this issue for a lot of time.
Could suggest anything else which could reduce the power draw?

Thanking you
Yours faithfully
Sridhar Singhal
